name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and generate reports
        run: mvn clean verify site

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: metric-reports
          path: |
            target/site/jacoco/**
            target/site/spotbugs.html
            target/site/checkstyle.html
