name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 1ª pasada: compila, testea y ejecuta SpotBugs/Checkstyle
      - name: Build & Verify
        run: mvn -B clean verify || true      #  ⬅️  ignora fallos deliberadamente

      # 2ª pasada: genera el sitio (HTML) con los informes
      - name: Generate Site
        run: mvn -B site || true              #  ⬅️  produce target/site/*

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: metric-reports
          path: |
            target/site/jacoco
            target/site/spotbugs.html
            target/site/checkstyle.html
